apiVersion: v1
kind: Service
metadata:
  name: medicure-service-rtp
  namespace: medicure
spec:
  type: NodePort
  selector:
    app: medicure-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
